### ISSUE TITLE
English termynology

### ISSUE THREAD

**Issue by YogurtTheHorse** [nntarasov/podbel#15]
Use english termynology instead of russian, because it's really hard to understand (IMHO)

**Comment by YogurtTheHorse** [comment]
In the same time I do not know where are these questions from, so maybe they are terrible by design (c'mon, check syntax knoweldge instead of programming)

**Comment by hyperion-cs** [comment]
This is quite a specific test of some university, which must necessarily be in Russian by design. Not a way to learn and/or test general-purpose C# knowledge.
